### PR TITLE
Add support for `:let-heredoc` and fix `:lang-heredoc`

### LINKED ISSUE #101: The :let-heredoc feature isn't supported
Using [the example from help](https://github.com/vim/vim/blob/2e693a88b24dc6b12883fad78ff2cb9cd4469c98/runtime/doc/eval.txt#L11412-L11421):

```vim
let var1 =<< END
Sample text 1
    Sample text 2
Sample text 3
END

let data =<< trim DATA
	1 2 3 4
	5 6 7 8
DATA
```

## Possible output syntax tree

```
(let_statement
  (identifier)
  (heredoc
    (heredoc_endmarker)
    (heredoc_body)
    (heredoc_endmarker)))

(let_statement
  (identifier)
  (heredoc
    (heredoc_options)
    (heredoc_endmarker)
    (heredoc_body)
    (heredoc_endmarker)))
```

Or as an output of tree-sitter's playground:

```
let_statement [0, 0] - [4, 3]
  identifier [0, 4] - [0, 8]
  heredoc [0, 13] - [4, 3]
    heredoc_endmarker [0, 13] - [0, 16]
    heredoc_body [1, 0] - [3, 13]
    heredoc_endmarker [4, 0] - [4, 3]
let_statement [6, 0] - [9, 4]
  identifier [6, 4] - [6, 8]
  heredoc_options [6, 13] - [6, 17]
  heredoc_endmarker [6, 18] - [6, 22]
  heredoc_body [7, 0] - [8, 8]
  heredoc_endmarker [9, 0] - [9, 4]
```

## Current output syntax tree

```
let_statement [0, 0] - [0, 3]
ERROR [0, 4] - [0, 16]
  identifier [0, 4] - [0, 8]
  keyword [0, 13] - [0, 16]
user_command [1, 0] - [1, 13]
  command_name [1, 0] - [1, 6]
  arguments [1, 7] - [1, 13]
    command_argument [1, 7] - [1, 11]
    command_argument [1, 12] - [1, 13]
user_command [2, 4] - [2, 17]
  command_name [2, 4] - [2, 10]
  arguments [2, 11] - [2, 17]
    command_argument [2, 11] - [2, 15]
    command_argument [2, 16] - [2, 17]
user_command [3, 0] - [3, 13]
  command_name [3, 0] - [3, 6]
  arguments [3, 7] - [3, 13]
    command_argument [3, 7] - [3, 11]
    command_argument [3, 12] - [3, 13]
user_command [4, 0] - [4, 3]
  command_name [4, 0] - [4, 3]
let_statement [6, 0] - [6, 3]
ERROR [6, 4] - [8, 8]
  identifier [6, 4] - [6, 8]
  keyword [6, 13] - [6, 17]
  keyword [6, 18] - [6, 22]
user_command [9, 0] - [9, 4]
  command_name [9, 0] - [9, 4]
```

### PR DESCRIPTION
**Pull request by jchros**
A backward-incompatible change that will require to modify both the `highlight.scm` and `injections.scm` query files in nvim-treesitter (`highlight.scm` file should be modified to support `:let-heredoc`s and `injections.scm` should be modified to accommodate for the removal of the named `chunk` nodes inside of the `script` nodes).

Should close #101.

### CODE REVIEW

**Comment by clason** [comment]
On this note: @vigoux would you consider including queries in this repo as well? I know they are not strictly necessary, but if such breaking changes would include correspondingly updated queries (and I knew that), this would make my job as nvim-treesitter maintainer _much_ easier since I didn't have to trawl through commits for `grammar.js` changes and fumble my way through fixing the errors when our "Update lockfile.json" action tries to update the parser...

**Comment by jchros** [comment]
I'll just provide the queries needed here:

In `injections.scm`, the first five lines should be replaced with:
```
(lua_statement (script (body) @lua))
(ruby_statement (script (body) @ruby))
(python_statement (script (body) @python))
(lua_statement (chunk) @lua)
(ruby_statement (chunk) @ruby)
(python_statement (chunk) @python)
;; If we support perl at some point...
;; (perl_statement (script (body) @perl))
;; (perl_statement (chunk) @perl)
```

And in `highlights.scm`, the following line should be added:
```
(let_heredoc (body) @string)
```

**Comment by vigoux** [comment]
Maybe we can do even better and actually add tests with queries for this, so that we correctly handle all this a detect breaking changes easier.

For more information, see https://tree-sitter.github.io/tree-sitter/syntax-highlighting#unit-testing

I think I'll merge that now and add the test today, so that we get the ball rolling.

**Comment by vigoux** [comment]
So, you'll have to rebase on master, and move your tests around a bit.
I am sorry for the delay this causes, but this will make our testing more robust.

**Comment by vigoux** [comment]
So, you should see all the relevant information about the testing in the commits I did, but this still needs a bit of documentation.

Basically, we can now test both highlights and queries, when running `npm test` using a pretty straighforward directory structure.

For the record, I opened https://github.com/tree-sitter/tree-sitter/issues/1790 to ask about those weird hacks we have to do, and maybe automate them.
We'll see how it goes.

**Comment by jchros** [comment]
Done.

**Comment by vigoux** [comment]
Rebase needed again after the merge of #106

**Comment by jchros** [comment]
Done.

**Comment by jchros** [comment]
It turns out I confused the syntax for testing highlight queries with the tests for injections queries.  I've written the injection tests in `tests/injections`.

File: grammar.js [hunk 1]
```diff
@@ -321,14 +322,13 @@ module.exports = grammar({
 
     chunk: ($) => /[^\n]+/,
 
-    _script_line: ($) => seq(optional($.chunk), '\n'),
+    _script_line: ($) => seq(optional(alias($.chunk, 'chunk')), '\n'),
```
[the remark this answers is not in the document]
Comment (jchros) [reply grammar.js:325]: I thought it was better to make each individual line an anonymous node rather than a named one to make the generated AST lighter, but I guess I can undo the change when I get home.

File: grammar.js [hunk 2]
```diff
@@ -542,6 +552,13 @@ module.exports = grammar({
         )
       ),
 
+    let_heredoc: ($) =>
```
[the remark this answers is not in the document]
Comment (jchros) [reply grammar.js:555]: I do think that naming the rule itself `heredoc` would be confusing (since there are two types of heredocs, the name wouldn't describe which), but using an alias in `let_statement` would be a good idea I think.  I'll work on it when I get home.

File: grammar.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (vigoux) [reply grammar.js:325]: No but as it is right now, this is redundant:
```suggestion
    _script_line: ($) => seq(optional($.chunk), '\n'),
```

[the remark this answers is not in the document]
Comment (jchros) [reply grammar.js]: Done, I have rebased it onto the first diverging commit of the branch and made the necessary changes in the `test/corpus` dir.

File: src/scanner.c [hunk 3]
```diff
@@ -292,20 +295,46 @@ bool try_lex_script_start(Scanner *scanner, TSLexer *lexer)
   }
   skip_space_tabs(lexer);
 
+  // Skip :let-heredoc parameters (trim, eval, etc.)
```
Comment (vigoux) [inline src/scanner.c:298]: Wo boy, maybe we want to capture those at some point ? At least leave it as a TODO

**Review by vigoux — COMMENTED** [review]
So this PR is pretty well tested, but I'd like to review it a bit more before merging.

Since it touches the `scanner.c` in a non-trivial way, I'll start a fuzzing campain on it too, for good measure.

**Comment by vigoux** [comment]
The fuzzing campain went well, these changes are great (even if they are breaking). Thanks a lot !

File: src/scanner.c (hunk 3 above)
Comment (jchros) [reply src/scanner.c]: I ended up marking it as a TODO to avoid giving extra work to both of us; we could fix this in another PR.

**Comment by jchros** [comment]
I was working on fixing the TODO, but I found out that the grammar incorrectly rejected some edge cases (see [34710d4's commit message](https://github.com/vigoux/tree-sitter-viml/pull/107/commits/34710d4e9b8443b18076b09a07040182d0d6564f)), hence the new commit.

**Comment by jchros** [comment]
> I was working on fixing the TODO, but I found out that the grammar incorrectly rejected some edge cases (see [34710d4's commit message](https://github.com/vigoux/tree-sitter-viml/pull/107/commits/34710d4e9b8443b18076b09a07040182d0d6564f)), hence the new commit.

By the way, I was able to fix the TODO.  Should I put the changes in this pull request or do you prefer that I wait until this pull request is merged to make a new one?

**Comment by vigoux** [comment]
Let's all have in this PR, it is getting pretty big, and having it self-contained will help with maintaining.

File: grammar.js [hunk 4]
```diff
@@ -549,6 +560,19 @@ module.exports = grammar({
...
```
Comment (vigoux) [inline grammar.js:563]:
```suggestion
    _let_heredoc: ($) =>
```

File: grammar.js [hunk 5]
```diff
@@ -537,8 +543,13 @@ module.exports = grammar({
...
           $.list_assignment,
         ),
-        '=',
-        $._expression,
+        choice(
+          seq(
+            '=',
+            $._expression,
+          ),
+          alias($.let_heredoc, $.heredoc),
```
Comment (vigoux) [inline grammar.js:551]:
```suggestion
          alias($._let_heredoc, $.heredoc),
```

File: grammar.js [hunk 6]
```diff
@@ -549,6 +560,19 @@ module.exports = grammar({
...
+        '=<<',
+        repeat(alias($._let_heredoc_parameter, $.parameter)),
+        alias($._let_heredoc_marker, $.marker_definition),
+        optional($.comment),
+        '\n',
+        alias(repeat($._heredoc_line), $.body),
+        alias($._heredoc_end, $.endmarker),
+      ),
+
+    _let_heredoc_parameter: ($) => /[a-z]\S*/,
```
Comment (vigoux) [inline grammar.js:574]: Aren't these from a specific set ? If they do, I'd rather have:
```suggestion
    _let_heredoc_parameter: ($) => choice('trim', 'eval'),
```

And also, could you add a little comment so that we can easily find the reference of this in the documentation ?

File: queries/highlights.scm [hunk 7]
```diff
@@ -151,6 +151,10 @@
 (pattern) @string.special
 (pattern_multi) @string.regex
 (filename) @string
+(let_statement (heredoc (body) @string))
+(const_statement (heredoc (body) @string))
+((heredoc (parameter) @keyword (#any-of? @keyword "trim" "eval")))
+((heredoc (parameter) @error (#not-any-of? @error "trim" "eval")))
```
Comment (vigoux) [inline queries/highlights.scm:157]: With the other changes mentionned, this becomes:
```suggestion
((heredoc (parameter) @keyword))

```

**Review by vigoux — COMMENTED** [review]
We are almost there, so great job !

A final note: the last two file (python and ruby injections) don't test anything, you need to add comments with the expected captures withing them.

File: grammar.js (hunk 6 above)
Comment (jchros) [reply grammar.js:574]: I initially thought it might be better for forward compatibility to define it the way I did given that these always start with a lowercase character, but you're right, specifying the list of valid `:let-heredoc` parameters would simplify things.

NB:`eval` only exists in Vim at the time I'm writing this.

**Comment by jchros** [comment]
The three commits I've made should address your comments.

By the way, I don't understand how the whole fuzzing thing works, but since fixing the TODO required me to change `src/scanner.c` in a non-trivial way, it's probably be a good idea to run the fuzzer again.

**Comment by vigoux** [comment]
The fuzzing setup (for now) is not really helpfull ass we need to dive into the logs in order to reproduce things.

I'll setup the fuzzing so that it is automatically triggered when changing the `src/scanner.c`.

**Comment by vigoux** [comment]
If you rebase on latest master, the fuzzing should be trigger automatically.

File: queries/highlights.scm [hunk 8]
```diff
@@ -151,6 +151,9 @@
 (pattern) @string.special
 (pattern_multi) @string.regex
 (filename) @string
+(let_statement (heredoc (body) @string))
+(const_statement (heredoc (body) @string))
```
Comment (vigoux) [inline queries/highlights.scm:155]: Maybe even simpler:
```suggestion
(heredoc (body) @string)
```
